version: "3"

services:
  nginx:  
    image: nginx:latest
    container_name: nginx # comment for unscaled service
    depends_on:
      - search
    ports:
      - 8082:8082
    volumes:
      - ./conf:/etc/nginx/conf.d/
      
  mdb:
    container_name: mdb
    image: mongo:latest
    restart: on-failure
    ports: 
      - 27017:27017
    volumes:
      - mdb:/data/db
    logging:
      driver: none

  lcs:
    build:
      context: ./contentResponseSystem
      dockerfile: Dockerfile
    image: dkt_lcs:latest
    container_name: dkt-lcs
    depends_on:
      - mdb
    restart: unless-stopped
    ports:
      - 8083:8083
    environment:
      - MONGO_URI=mongodb://mdb:27017/LikeAndComment

  chat:
    build:
      context: ./chatSystem
      dockerfile: Dockerfile
    image: dkt_chat:latest
    container_name: dkt-chat
    depends_on:
      - mdb
    restart: unless-stopped
    ports:
      - 8085:8085
    environment:
      - MONGO_URI=mongodb://mdb:27017/chat_sys

  notif:
    build:
      context: ./notifSystem
      dockerfile: Dockerfile
    image: dkt_notif:latest
    container_name: dkt-notif
    depends_on:
      - mdb
    restart: unless-stopped
    ports:
      - 8089:8089
    environment:
      - MONGO_URI=mongodb://mdb:27017/Notifications

  util:
    build:
      context: ./userUtilSystem
      dockerfile: Dockerfile
    image: dkt_util:latest
    container_name: dkt-util
    ports:
      - 8080:8080
    depends_on:
      - mdb
    restart: unless-stopped
    environment:
      - UTIL_DB=mongodb://mdb:27017/user_util_db

  mail:
    build:
      context: ./mails
      dockerfile: Dockerfile
    image: dkt_mail:latest
    container_name: dkt-mail
    restart: unless-stopped
    ports:
      - 8087:8087

  tts:
    build:
      context: ./ttsSystem
      dockerfile: Dockerfile
    image: dkt_tts:latest
    container_name: dkt-tts
    restart: unless-stopped
    ports:
      - 8088:8088

  search:
    build:
      context: ./elasticSystem
      dockerfile: Dockerfile
    image: dkt_search:latest
    # container_name: dkt-search # uncomment for unscaled service
    restart: unless-stopped
    # ports:  # uncomment for unscaled service
      # - 8082:8082 # uncomment for unscaled service

  cloud:
    build:
      context: ./cloudinarySystem
      dockerfile: Dockerfile
    image: dkt_cloud:latest
    container_name: dkt-cloud
    restart: unless-stopped
    ports:
      - 8081:8081
    # environment:

volumes:
  mdb:
  nginx:
